services:
  - type: web
    name: crm-backend
    env: php
    plan: starter
    buildCommand: composer install --no-dev --optimize-autoloader
    startCommand: php artisan serve --host=0.0.0.0 --port=$PORT
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        fromDatabase:
          name: crm-database
          property: host
      - key: DB_PORT
        fromDatabase:
          name: crm-database
          property: port
      - key: DB_DATABASE
        fromDatabase:
          name: crm-database
          property: database
      - key: DB_USERNAME
        fromDatabase:
          name: crm-database
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: crm-database
          property: password
    healthCheckPath: /api/test

databases:
  - name: crm-database
    plan: starter
